#!/usr/bin/env bash
# Script to configure domain to load balancer
domain=$1

# Check if subdomain is given and act accordingly
subdomains=("www" "lb-01" "web-01" "web-02")
if [ -z "$2" ]
then
	for subdomain in "${subdomains[@]}"
	do
		url="$subdomain.$domain"
		record=$(dig $url | grep -A1 'ANSWER SECTION:' | awk '{print $4}' | tr -d '\n')
		destination=$(dig $url | grep -A1 'ANSWER SECTION:' | awk '{print $5}' | tr -d '\n')
		echo "The subdomain $subdomain is a $record record and points to $destination"
	done
else
	subdomain=$2
	url="$subdomain.$domain"
	record=$(dig $url | grep -A1 'ANSWER SECTION:' | awk '{print $4}' | tr -d '\n')
	destination=$(dig $url | grep -A1 'ANSWER SECTION:' | awk '{print $5}' | tr -d '\n')
	echo "The subdomain $subdomain is a $record record and points to $destination"
fi	
