#!/usr/bin/env bash
# Configuring /redirectme to another link
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
sudo chmod -R 777 /var/www/html
echo 'Hello World!' > /var/www/html/index.nginx-debian.htmli
sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
service nginx start
