#!/usr/bin/env bash
# Copying one file to another server
path_to_file=$1
ip_of_server=$2
username=$3
path_to_private_key=$4
if [ $# -lt 4 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	scp -o StrictHostKeyChecking=no -i "$path_to_private_key" "$path_to_file" "$username@$ip_of_server":~
fi
