#!/usr/bin/env bash
#Installing HAProxy on Ubuntu
sudo apt-get -y update
sudo apt-get -y install haproxy
details="\
frontend def_balancer
    bind *:80
    default_backend web-servers

backend web-servers
    balance roundrobin
    server 290334-web-01 54.209.208.92:80 check
    server 290334-web-02 54.209.160.70:80 check
"
echo "$details" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo sed -i 's/^ENABLED=./ENABLED=1/' /etc/default/haproxy
sudo service haproxy restart
